// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -package=usecases -destination=interfaces_mock.go
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	entities "github.com/mikalai-mitsin/example/internal/app/posts/entities/tag"
	dtx "github.com/mikalai-mitsin/example/internal/pkg/dtx"
	log "github.com/mikalai-mitsin/example/internal/pkg/log"
	uuid "github.com/mikalai-mitsin/example/internal/pkg/uuid"
	fxevent "go.uber.org/fx/fxevent"
	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MocktagService is a mock of tagService interface.
type MocktagService struct {
	ctrl     *gomock.Controller
	recorder *MocktagServiceMockRecorder
	isgomock struct{}
}

// MocktagServiceMockRecorder is the mock recorder for MocktagService.
type MocktagServiceMockRecorder struct {
	mock *MocktagService
}

// NewMocktagService creates a new mock instance.
func NewMocktagService(ctrl *gomock.Controller) *MocktagService {
	mock := &MocktagService{ctrl: ctrl}
	mock.recorder = &MocktagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagService) EXPECT() *MocktagServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktagService) Create(arg0 context.Context, arg1 dtx.TX, arg2 entities.TagCreate) (entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocktagServiceMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktagService)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MocktagService) Delete(arg0 context.Context, arg1 dtx.TX, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MocktagServiceMockRecorder) Delete(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocktagService)(nil).Delete), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MocktagService) Get(arg0 context.Context, arg1 uuid.UUID) (entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocktagServiceMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocktagService)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MocktagService) List(arg0 context.Context, arg1 entities.TagFilter) ([]entities.Tag, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].([]entities.Tag)
	ret1, _ := ret[1].(uint64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MocktagServiceMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MocktagService)(nil).List), arg0, arg1)
}

// Update mocks base method.
func (m *MocktagService) Update(arg0 context.Context, arg1 dtx.TX, arg2 entities.TagUpdate) (entities.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(entities.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MocktagServiceMockRecorder) Update(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocktagService)(nil).Update), arg0, arg1, arg2)
}

// MocktagEventService is a mock of tagEventService interface.
type MocktagEventService struct {
	ctrl     *gomock.Controller
	recorder *MocktagEventServiceMockRecorder
	isgomock struct{}
}

// MocktagEventServiceMockRecorder is the mock recorder for MocktagEventService.
type MocktagEventServiceMockRecorder struct {
	mock *MocktagEventService
}

// NewMocktagEventService creates a new mock instance.
func NewMocktagEventService(ctrl *gomock.Controller) *MocktagEventService {
	mock := &MocktagEventService{ctrl: ctrl}
	mock.recorder = &MocktagEventServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagEventService) EXPECT() *MocktagEventServiceMockRecorder {
	return m.recorder
}

// Created mocks base method.
func (m *MocktagEventService) Created(arg0 context.Context, arg1 dtx.TX, arg2 entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MocktagEventServiceMockRecorder) Created(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MocktagEventService)(nil).Created), arg0, arg1, arg2)
}

// Deleted mocks base method.
func (m *MocktagEventService) Deleted(arg0 context.Context, arg1 dtx.TX, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deleted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deleted indicates an expected call of Deleted.
func (mr *MocktagEventServiceMockRecorder) Deleted(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deleted", reflect.TypeOf((*MocktagEventService)(nil).Deleted), arg0, arg1, arg2)
}

// Updated mocks base method.
func (m *MocktagEventService) Updated(arg0 context.Context, arg1 dtx.TX, arg2 entities.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updated", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updated indicates an expected call of Updated.
func (mr *MocktagEventServiceMockRecorder) Updated(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updated", reflect.TypeOf((*MocktagEventService)(nil).Updated), arg0, arg1, arg2)
}

// Mocklogger is a mock of logger interface.
type Mocklogger struct {
	ctrl     *gomock.Controller
	recorder *MockloggerMockRecorder
	isgomock struct{}
}

// MockloggerMockRecorder is the mock recorder for Mocklogger.
type MockloggerMockRecorder struct {
	mock *Mocklogger
}

// NewMocklogger creates a new mock instance.
func NewMocklogger(ctrl *gomock.Controller) *Mocklogger {
	mock := &Mocklogger{ctrl: ctrl}
	mock.recorder = &MockloggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklogger) EXPECT() *MockloggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *Mocklogger) Debug(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockloggerMockRecorder) Debug(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*Mocklogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *Mocklogger) Error(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockloggerMockRecorder) Error(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*Mocklogger)(nil).Error), varargs...)
}

// Fatal mocks base method.
func (m *Mocklogger) Fatal(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockloggerMockRecorder) Fatal(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*Mocklogger)(nil).Fatal), varargs...)
}

// Info mocks base method.
func (m *Mocklogger) Info(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockloggerMockRecorder) Info(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*Mocklogger)(nil).Info), varargs...)
}

// LogEvent mocks base method.
func (m *Mocklogger) LogEvent(event fxevent.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogEvent", event)
}

// LogEvent indicates an expected call of LogEvent.
func (mr *MockloggerMockRecorder) LogEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogEvent", reflect.TypeOf((*Mocklogger)(nil).LogEvent), event)
}

// Logger mocks base method.
func (m *Mocklogger) Logger() *zap.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*zap.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockloggerMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*Mocklogger)(nil).Logger))
}

// Named mocks base method.
func (m *Mocklogger) Named(name string) log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Named", name)
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// Named indicates an expected call of Named.
func (mr *MockloggerMockRecorder) Named(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Named", reflect.TypeOf((*Mocklogger)(nil).Named), name)
}

// Panic mocks base method.
func (m *Mocklogger) Panic(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panic", varargs...)
}

// Panic indicates an expected call of Panic.
func (mr *MockloggerMockRecorder) Panic(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*Mocklogger)(nil).Panic), varargs...)
}

// Print mocks base method.
func (m *Mocklogger) Print(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Print", varargs...)
}

// Print indicates an expected call of Print.
func (mr *MockloggerMockRecorder) Print(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*Mocklogger)(nil).Print), varargs...)
}

// SetLevel mocks base method.
func (m *Mocklogger) SetLevel(lvl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLevel", lvl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLevel indicates an expected call of SetLevel.
func (mr *MockloggerMockRecorder) SetLevel(lvl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLevel", reflect.TypeOf((*Mocklogger)(nil).SetLevel), lvl)
}

// Warn mocks base method.
func (m *Mocklogger) Warn(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockloggerMockRecorder) Warn(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*Mocklogger)(nil).Warn), varargs...)
}

// Warning mocks base method.
func (m *Mocklogger) Warning(msg string, fields ...log.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warning", varargs...)
}

// Warning indicates an expected call of Warning.
func (mr *MockloggerMockRecorder) Warning(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*Mocklogger)(nil).Warning), varargs...)
}

// With mocks base method.
func (m *Mocklogger) With(fields ...log.Field) log.Logger {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "With", varargs...)
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockloggerMockRecorder) With(fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*Mocklogger)(nil).With), fields...)
}

// WithContext mocks base method.
func (m *Mocklogger) WithContext(ctx context.Context) log.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(log.Logger)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockloggerMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*Mocklogger)(nil).WithContext), ctx)
}

// MockdtxManager is a mock of dtxManager interface.
type MockdtxManager struct {
	ctrl     *gomock.Controller
	recorder *MockdtxManagerMockRecorder
	isgomock struct{}
}

// MockdtxManagerMockRecorder is the mock recorder for MockdtxManager.
type MockdtxManagerMockRecorder struct {
	mock *MockdtxManager
}

// NewMockdtxManager creates a new mock instance.
func NewMockdtxManager(ctrl *gomock.Controller) *MockdtxManager {
	mock := &MockdtxManager{ctrl: ctrl}
	mock.recorder = &MockdtxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdtxManager) EXPECT() *MockdtxManagerMockRecorder {
	return m.recorder
}

// NewTx mocks base method.
func (m *MockdtxManager) NewTx() dtx.TX {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTx")
	ret0, _ := ret[0].(dtx.TX)
	return ret0
}

// NewTx indicates an expected call of NewTx.
func (mr *MockdtxManagerMockRecorder) NewTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTx", reflect.TypeOf((*MockdtxManager)(nil).NewTx))
}
