name: AI Code Review

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install openai reviewdog

      - name: Run AI Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Получаем diff изменений относительно master
          git fetch origin master
          git diff origin/master...HEAD > diff.patch

          # Создаем временный Python-скрипт для AI-ревью
          echo 'import os, openai
  code = open("diff.patch").read()
  prompt = f"""
  You are an expert Go developer.
  Review the following Go code. Suggest improvements in style, structure, and potential bugs.
Return each issue in the format: file:line:message
Here is the code:

  {code}
  """
response = openai.ChatCompletion.create(
    model="gpt-4",
messages=[{"role":"user","content": prompt}],
  temperature=0
  )
  print(response["choices"][0]["message"]["content"])
  ' > ai_review.py
  
  # Запускаем AI-ревью
  python3 ai_review.py
